version: "3.9"
services:
  web1:
    image: caddy:2.6.2-alpine
    volumes:
      - ./adx:/usr/share/caddy/
    ports:
      - 127.0.0.1:3001:80

  web2:
    image: caddy:2.6.2-alpine
    volumes:
      - ./kunden:/usr/share/caddy/
    ports:
      - 127.0.0.1:3002:80
